defaults: &defaults
  host: localhost
  allow_dynamic_fields: false
  autocreate_indexes: false
  identity_map_enabled: true
  include_root_in_json: false
  max_retries_on_connection_failure: 3
  parameterize_keys: true
  persist_in_safe_mode: false
  preload_models: false
  raise_not_found_error: true
  skip_version_check: false
  logger: true

development:
  host: ds031647.mongolab.com
  port: 31647
  username: heroku_app3584442
  password: e10db5l2ojnmbu738o5bun9385
  database: heroku_app3584442

test:
  <<: *defaults
  database: energy_pet_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

# For Heroku
# production:
#  uri: <%= ENV['MONGOHQ_URL'] %>
# or
#  uri: <%= ENV['MONGOLAB_URI'] %>

